/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    demandes: Demande;
    courses: Course;
    teachers: Teacher;
    'pricing-plans': PricingPlan;
    rooms: Room;
    gallery: Gallery;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    demandes: DemandesSelect<false> | DemandesSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    teachers: TeachersSelect<false> | TeachersSelect<true>;
    'pricing-plans': PricingPlansSelect<false> | PricingPlansSelect<true>;
    rooms: RoomsSelect<false> | RoomsSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Demandes envoyées depuis le site (essai, inscription, location, cours privé). Rien n'est réservé automatiquement : chaque demande attend ta réponse. Tu reçois aussi chaque demande par mail.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "demandes".
 */
export interface Demande {
  id: number;
  /**
   * Rempli automatiquement à l'envoi. Sert de titre dans la liste.
   */
  resume?: string | null;
  type: 'essai' | 'inscription' | 'location' | 'prive';
  /**
   * Le cours que la personne veut essayer.
   */
  cours?: (number | null) | Course;
  /**
   * La formule choisie sur la page Tarifs.
   */
  formule?: (number | null) | PricingPlan;
  salle?: (number | null) | Room;
  /**
   * Déclaré par la personne elle-même.
   */
  niveau?: ('debutant' | 'intermediaire' | 'avance' | 'ne-sais-pas') | null;
  /**
   * En texte libre, tel que saisi sur le site.
   */
  dateSouhaitee?: string | null;
  personnes?: number | null;
  message?: string | null;
  prenom: string;
  /**
   * Pour répondre : répondre au mail de notification reçu écrit directement à cette adresse.
   */
  email: string;
  /**
   * Facultatif sur le site : peut être vide.
   */
  telephone?: string | null;
  /**
   * À faire avancer au fil du traitement. Changer le statut ne prévient pas la personne : la réponse se fait par mail ou par téléphone.
   */
  statut: 'nouvelle' | 'en-cours' | 'confirmee' | 'sans-suite';
  /**
   * Visibles seulement ici, jamais envoyées au visiteur.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Le planning de la semaine. Chaque cours apparaît dans le Calendrier, sur la page de son ou sa prof, et dans la liste des cours d'essai proposés aux visiteurs. Supprimer un cours le retire partout.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  /**
   * Ex : Heels. Le niveau se met dans le champ suivant.
   */
  title: string;
  /**
   * Identifiant du cours dans les liens de réservation, par exemple heels-mardi-19-00. Rempli tout seul ; à ne changer que si le cours n'est pas encore en ligne, sinon les liens existants se cassent.
   */
  slug?: string | null;
  /**
   * Ligne sous le titre. Pas seulement un niveau : aussi une tranche d'âge (10-14 ans) ou une modalité (Sous demande de réservation).
   */
  level?: string | null;
  dayOfWeek: 'Lundi' | 'Mardi' | 'Mercredi' | 'Jeudi' | 'Vendredi' | 'Samedi' | 'Dimanche';
  /**
   * Format 24h, ex : 19:00 ou 8:00.
   */
  startTime: string;
  /**
   * Format 24h, ex : 20:30.
   */
  endTime: string;
  /**
   * Laisser vide si le cours n'a pas de prof attitré·e (ex : Training libre).
   */
  teacher?: (number | null) | Teacher;
  /**
   * Affichée en haut à droite de la carte du calendrier, ex : Studio A.
   */
  room?: string | null;
  /**
   * Les plus petits nombres passent en premier (1, 2, 3…).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * L'équipe. Une personne n'apparaît sur la page Profs, avec sa page personnelle, que si elle a un portrait ET une présentation. Sans les deux, elle reste choisissable comme prof d'un cours.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teachers".
 */
export interface Teacher {
  id: number;
  /**
   * Tel qu'affiché sur le site, ex : Léna Bapz.
   */
  name: string;
  /**
   * Fin de l'adresse de sa page, par exemple lena-bapz pour /profs/lena-bapz. Rempli tout seul à partir du nom ; à ne changer que si la page n'est pas encore en ligne, sinon les liens existants se cassent.
   */
  slug?: string | null;
  /**
   * Affichée à droite du nom sur la page Profs (ex : Heels).
   */
  discipline?: string | null;
  /**
   * Format paysage, environ 1086 x 944 (un peu plus large que haut). Le visage vers le haut de l'image.
   */
  photo?: (number | null) | Media;
  /**
   * Un paragraphe par entrée. Le texte entre ** ** apparaît en blanc et en gras sur le site, ex : **Heels**.
   */
  bio?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Ordre sur la page Profs : les plus petits nombres passent en premier (1, 2, 3…).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Toutes les images du site. Une image ajoutée depuis une fiche (portrait, photo de salle…) arrive ici automatiquement. Supprimer une image la retire aussi des pages qui l'utilisent.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Une phrase courte qui dit ce qu'on voit, ex : « Léna en cours de heels ». Lue par les personnes malvoyantes et par Google.
   */
  alt: string;
  _key?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Formules de la page Tarifs. Le bouton « Choisir » de chaque carte ouvre une demande d'inscription avec la formule déjà sélectionnée.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-plans".
 */
export interface PricingPlan {
  id: number;
  /**
   * Détermine dans quelle section de la page Tarifs la formule apparaît. « Offre d'essai » s'affiche en bandeau pleine largeur, en haut de la page.
   */
  group: 'carte' | 'abonnement' | 'essai';
  /**
   * Au-dessus du prix, en petites capitales, ex : "Le + populaire". Facultatif.
   */
  label?: string | null;
  /**
   * Sous le prix, en capitales, ex : Carte 10 cours.
   */
  name: string;
  /**
   * Identifiant de la formule dans les liens de réservation, par exemple carte-10-cours. Rempli tout seul à partir du nom ; à ne changer que si la formule n'est pas encore en ligne.
   */
  slug?: string | null;
  /**
   * Avec la devise, ex : "160 €".
   */
  price: string;
  /**
   * Accolé au prix, ex : "/ an". Vide si sans objet.
   */
  period?: string | null;
  /**
   * Sert à afficher « soit X € le cours » sous le prix, ce qui permet de comparer les formules. Mettre 10 pour une carte de 10 cours ; pour un abonnement à l'année, le nombre de cours sur la saison (par exemple 34 semaines = 34). Laisser vide pour ne rien afficher.
   */
  sessionsIncluded?: number | null;
  /**
   * Une ou deux phrases courtes sous le nom, ex : Valable 4 mois, pour tous les cours.
   */
  description?: string | null;
  /**
   * Bordure plus marquée et petit libellé en blanc. À réserver à une formule par section, sinon plus rien ne ressort.
   */
  highlighted?: boolean | null;
  /**
   * Les plus petits nombres passent en premier (1, 2, 3…), dans chaque section.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Salles à louer, affichées en bas de la page Tarifs. Le bouton « Choisir » ouvre une demande de location avec la salle déjà sélectionnée.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms".
 */
export interface Room {
  id: number;
  name: string;
  /**
   * Identifiant de la salle dans les liens de réservation, par exemple salle-a. Rempli tout seul à partir du nom ; à ne changer que si la salle n'est pas encore en ligne.
   */
  slug?: string | null;
  /**
   * Format paysage, environ 2,7 fois plus large que haut (ex : 1500 x 562). Sans photo, la carte s'affiche sans image.
   */
  photo?: (number | null) | Media;
  /**
   * Avec la devise, ex : "30 €". Laisser vide pour afficher « Tarif sur demande ».
   */
  price?: string | null;
  /**
   * Accolé au tarif, ex : "/ heure". Vide si sans objet.
   */
  period?: string | null;
  /**
   * Nombre de personnes maximum, en chiffres.
   */
  capacity?: number | null;
  /**
   * En chiffres, sans « m² ».
   */
  area?: number | null;
  /**
   * Un équipement par ligne, ex : Climatisation. Ils s'affichent à la suite, séparés par des virgules.
   */
  equipment?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * À remplir seulement si la salle n'est pas encore ouverte (ex : 2027). Le bouton de réservation est alors masqué. Vider le champ le jour de l'ouverture.
   */
  availableFrom?: string | null;
  /**
   * Les plus petits nombres passent en premier (1, 2, 3…).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Photos de la page Galerie. La page est encore en préparation : les photos ajoutées ici n'y apparaissent pas pour l'instant.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  image: number | Media;
  /**
   * Ce qu'on voit sur la photo, en une phrase courte.
   */
  alt: string;
  /**
   * Les plus petits nombres passent en premier (1, 2, 3…).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Les personnes qui peuvent se connecter à cette administration. Tous les comptes ont les mêmes droits.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'demandes';
        value: number | Demande;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'teachers';
        value: number | Teacher;
      } | null)
    | ({
        relationTo: 'pricing-plans';
        value: number | PricingPlan;
      } | null)
    | ({
        relationTo: 'rooms';
        value: number | Room;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "demandes_select".
 */
export interface DemandesSelect<T extends boolean = true> {
  resume?: T;
  type?: T;
  cours?: T;
  formule?: T;
  salle?: T;
  niveau?: T;
  dateSouhaitee?: T;
  personnes?: T;
  message?: T;
  prenom?: T;
  email?: T;
  telephone?: T;
  statut?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  level?: T;
  dayOfWeek?: T;
  startTime?: T;
  endTime?: T;
  teacher?: T;
  room?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teachers_select".
 */
export interface TeachersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  discipline?: T;
  photo?: T;
  bio?:
    | T
    | {
        text?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-plans_select".
 */
export interface PricingPlansSelect<T extends boolean = true> {
  group?: T;
  label?: T;
  name?: T;
  slug?: T;
  price?: T;
  period?: T;
  sessionsIncluded?: T;
  description?: T;
  highlighted?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms_select".
 */
export interface RoomsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  photo?: T;
  price?: T;
  period?: T;
  capacity?: T;
  area?: T;
  equipment?:
    | T
    | {
        item?: T;
        id?: T;
      };
  availableFrom?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  image?: T;
  alt?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  _key?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Textes et coordonnées communs à tout le site : bannière d'accueil, adresse, horaires, Instagram, logo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Le grand titre de l'accueil. Un retour à la ligne dans ce champ coupe le titre au même endroit sur le site.
   */
  heroTitle: string;
  /**
   * Le texte sous le titre. Les retours à la ligne sont conservés. Il sert aussi de description du studio pour Google.
   */
  heroSubtitle?: string | null;
  /**
   * Texte du bouton blanc de la bannière, qui ouvre une demande de cours d'essai. Ex : "Cours d'essai - 10 €". Penser à le mettre à jour si le prix de l'essai change dans Tarifs.
   */
  trialLabel?: string | null;
  /**
   * Numéro, rue et commune. Affichée sur la page Contact et transmise à Google.
   */
  address?: string | null;
  /**
   * Affichée dans la bannière et en pied de page, ex : Metz.
   */
  city?: string | null;
  /**
   * Ex : 06 12 34 56 78. Affiché sur la page Contact et transmis à Google. Laisser vide pour ne pas l'afficher.
   */
  phone?: string | null;
  /**
   * Une ligne par créneau, affichées sur la page Contact. Laisser vide : la rubrique Horaires n'apparaît pas.
   */
  openingHours?:
    | {
        /**
         * Ex : Lundi - Vendredi
         */
        days: string;
        /**
         * Ex : 17h - 22h, ou Fermé
         */
        hours: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Avec le @, ex : @bapzstudio. Affiché dans la bannière, en pied de page et sur la page Contact.
   */
  instagramHandle?: string | null;
  /**
   * Les mots qui défilent en bas de l'accueil. Les deux premiers apparaissent aussi au centre du pied de page : y mettre les disciplines phares.
   */
  marqueeItems?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Affiché dans un rond, en haut à gauche de chaque page. Fond transparent de préférence.
   */
  logo?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  trialLabel?: T;
  address?: T;
  city?: T;
  phone?: T;
  openingHours?:
    | T
    | {
        days?: T;
        hours?: T;
        id?: T;
      };
  instagramHandle?: T;
  marqueeItems?:
    | T
    | {
        text?: T;
        id?: T;
      };
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}